name: Publish
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: BlackAsLight/setup-wabt@v1.1.1
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: BlackAsLight/setup-binaryen@v1.1.1
        env:
          GH_TOKEN: ${{ github.token }}
      - run: deno task release
      - run: deno publish
