name: Publish
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: mwilliamson/setup-wabt-action@v1
      - uses: Aandreba/setup-binaryen@v1
      - run: deno task release
      - run: deno publish
