name: Publish
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: macos-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: brew install wabt binaryen
      - run: wat2wasm --version
      - run: wasm-opt --version
      - run: deno task release
      - run: deno publish
