name: Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        type: [debug, release]
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: mwilliamson/setup-wabt-action@v3.0
      - uses: Aandreba/setup-binaryen@v1.0.0
      - run: deno task ${{ matrix.type }}
      - run: deno test -P --no-prompt --doc
