name: Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        type: [debug, release]
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: BlackAsLight/setup-wabt@v1.0.0
      - uses: BlackAsLight/setup-binaryen-toolkit@v1.0.0
      - run: deno task ${{ matrix.type }}
      - run: deno test -P --no-prompt --doc
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: brew install wabt
      - run: wat2wasm --version
      - run: deno task debug
      - run: deno fmt --check
      - run: deno lint
  publish--dry-run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: brew install wabt
      - run: wat2wasm --version
      - run: deno task debug
      - run: deno publish --dry-run
